#!/usr/bin/perl

use strict;
use warnings;
use FindBin qw($Bin);
use File::Copy qw(copy);
use File::Temp qw(tempdir);

my $tmpdir = tempdir(CLEANUP => 1);

my $version = `$Bin/csshX -v 2>&1` || die "Cauld not get version from csshX";

if ($version =~ /csshX v(\S+)/) {
    $version = $1;
} else {
    die "Can't parse: $version";
}

print "Creating [csshX-$version.tgz]\n";

mkdir "$tmpdir/csshX-$version" || die "mkdir: $!";

open(MANIFEST, "< $Bin/MANIFEST") || die "Can't read MANIFEST: $!";
while(defined(my $file = <MANIFEST>)) {
    chomp($file);
    copy($file, "$tmpdir/csshX-$version/") || die "copy $file: $!";
}
close(MANIFEST);

chdir $tmpdir || die "chdir: $!";
system("tar", "cvfz", "$tmpdir/csshX-$version.tgz", "csshX-$version") && die "tar: $!";

system("$Bin/support/googlecode_upload.py", "--summary", "csshX v$version", "--labels", "OpSys-OSX,Type-Archive", "--project", "csshx", "$tmpdir/csshX-$version.tgz")
   && die "Upload returned: $?";

##rename("$tmpdir/csshX-$version.tgz", "$Bin/csshX-$version.tgz") || die "rename: $!";

print "Done.\n";

exit 0;

# vim: expandtab sw=4 ts=4 sts=4:

