/*
 *     Generated by class-dump 3.3.1 (64 bit).
 *
 *     class-dump is Copyright (C) 1997-1998, 2000-2001, 2004-2009 by Steve Nygard.
 */

#pragma mark Named Structures

struct AEDesc {
    unsigned int descriptorType;
    struct OpaqueAEDataStorageType **dataHandle;
};

struct OpaqueAEDataStorageType;

struct _NSRange {
    unsigned long long _field1;
    unsigned long long _field2;
};

#pragma mark -

/*
 * File: ScriptingBridge.framework/Versions/A/ScriptingBridge
 * Arch: Intel x86-64 (x86_64)
 *       Current version: 1.0.0, Compatibility version: 1.0.0
 *
 *       Objective-C Garbage Collection: Supported
 */

@protocol NSCoding
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
@end

@interface SBApplication : SBObject <NSCoding>
{
}

+ (id)applicationWithBundleIdentifier:(id)arg1;
+ (id)applicationWithURL:(id)arg1;
+ (id)applicationWithProcessIdentifier:(int)arg1;
+ (Class)applicationClassForDefinition:(id)arg1;
+ (id)definitionFromSdef:(id)arg1 basename:(id)arg2;
- (id)init;
- (BOOL)shouldCreateClasses;
- (id)initWithContext:(id)arg1;
- (id)initWithBundleIdentifier:(id)arg1;
- (id)initWithURL:(id)arg1;
- (id)initWithProcessIdentifier:(int)arg1;
- (id)initWithCoder:(id)arg1;
- (void)encodeWithCoder:(id)arg1;
- (BOOL)isRunning;
- (void)activate;
- (id)delegate;
- (void)setDelegate:(id)arg1;
- (unsigned int)launchFlags;
- (void)setLaunchFlags:(unsigned int)arg1;
- (int)sendMode;
- (void)setSendMode:(int)arg1;
- (long long)timeout;
- (void)setTimeout:(long long)arg1;
- (id)classNamesForCodes;
- (id)codesForPropertyNames;
- (id)classesForScriptingNames;
- (Class)classForScriptingClass:(id)arg1;

@end

@interface SBElementArray : NSMutableArray
{
    SBObject *_parent;
    unsigned int _elementCode;
    void *_reserved;
}

- (id)init;
- (id)initWithArray:(id)arg1 copyItems:(BOOL)arg2;
- (id)initWithContentsOfFile:(id)arg1;
- (id)initWithContentsOfURL:(id)arg1;
- (id)initWithObjects:(id *)arg1 count:(unsigned long long)arg2;
- (id)initWithObjects:(id)arg1;
- (id)initWithParent:(id)arg1 elementCode:(unsigned int)arg2;
- (void)dealloc;
- (Class)elementClass;
- (id)allObjects;
- (id)objectWithKeyForm:(unsigned int)arg1 keyData:(id)arg2;
- (id)objectAtIndex:(unsigned long long)arg1;
- (id)objectsAtIndexes:(id)arg1;
- (id)objectWithName:(id)arg1;
- (id)objectWithID:(id)arg1;
- (id)objectAtLocation:(id)arg1;
- (id)lastObject;
- (void)addObject:(id)arg1;
- (void)insertObject:(id)arg1 atIndex:(unsigned long long)arg2;
- (void)removeObjectAtIndex:(unsigned long long)arg1;
- (void)removeObjectWithName:(id)arg1;
- (void)removeObjectWithID:(id)arg1;
- (void)removeLastObject;
- (void)removeAllObjects;
- (void)replaceObjectAtIndex:(unsigned long long)arg1 withObject:(id)arg2;
- (unsigned long long)count;
- (id)copyWithZone:(struct _NSZone *)arg1;
- (id)mutableCopyWithZone:(struct _NSZone *)arg1;
- (BOOL)isEqual:(id)arg1;
- (Class)classForCoder;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)subarrayWithRange:(struct _NSRange)arg1;
- (id)filteredArrayUsingPredicate:(id)arg1;
- (void)filterUsingPredicate:(id)arg1;
- (id)valueForKey:(id)arg1;
- (void)setValue:(id)arg1 forKey:(id)arg2;
- (id)arrayByApplyingSelector:(SEL)arg1;
- (id)arrayByApplyingSelector:(SEL)arg1 withObject:(id)arg2;
- (void)makeObjectsPerformSelector:(SEL)arg1;
- (void)makeObjectsPerformSelector:(SEL)arg1 withObject:(id)arg2;
- (id)parent;
- (id)context;
- (unsigned int)elementCode;
- (id)get;
- (id)description;
- (id)descriptionWithLocale:(id)arg1;
- (id)debugDescription;
- (id)qualifiedSpecifier;

@end

@interface SBObject : NSObject <NSCoding>
{
    struct AEDesc _specifier;
    SBAppContext *_ctx;
    void *_reserved;
}

- (id)initWithContext:(id)arg1 specifier:(const struct AEDesc *)arg2;
- (id)initWithApplication:(id)arg1 specifier:(const struct AEDesc *)arg2;
- (id)initWithClass:(Class)arg1 properties:(id)arg2 data:(id)arg3;
- (id)init;
- (id)initWithProperties:(id)arg1;
- (id)initWithData:(id)arg1;
- (id)initWithElementCode:(unsigned int)arg1 properties:(id)arg2 data:(id)arg3;
- (void)finalize;
- (void)dealloc;
- (id)context;
- (const struct AEDesc *)specifier;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)childWithClass:(Class)arg1 code:(unsigned int)arg2 keyForm:(unsigned int)arg3 keyDesc:(const struct AEDesc *)arg4;
- (id)childWithClass:(Class)arg1 code:(unsigned int)arg2 keyForm:(unsigned int)arg3 keyData:(id)arg4;
- (id)childWithClass:(Class)arg1 code:(unsigned int)arg2 keyForm:(unsigned int)arg3 keyData:(const void *)arg4 length:(unsigned long long)arg5 type:(unsigned int)arg6;
- (id)childWithClass:(Class)arg1 code:(unsigned int)arg2 keyForm:(unsigned int)arg3 keyData:(id)arg4 type:(unsigned int)arg5;
- (id)positionBefore;
- (id)positionAfter;
- (id)propertyWithCode:(unsigned int)arg1;
- (id)propertyWithClass:(Class)arg1 code:(unsigned int)arg2;
- (id)elementArrayWithCode:(unsigned int)arg1;
- (id)elementWithCode:(unsigned int)arg1 atIndex:(int)arg2;
- (id)elementWithCode:(unsigned int)arg1 named:(id)arg2;
- (id)elementWithCode:(unsigned int)arg1 ID:(id)arg2;
- (id)sendEvent:(unsigned int)arg1 id:(unsigned int)arg2 parameters:(unsigned int)arg3;
- (id)sendEvent:(unsigned int)arg1 id:(unsigned int)arg2 format:(const char *)arg3;
- (id)get;
- (void)setTo:(id)arg1;
- (BOOL)isEqual:(id)arg1;
- (id)descriptionForSpecifier:(id)arg1;
- (id)specifierDescription;
- (id)description;
- (id)qualify:(id)arg1;
- (id)qualifiedSpecifier;
- (BOOL)isRangeSpecifier;

@end

@interface SBProxyByCode : SBProxy
{
    unsigned int _codeToCreate;
}

- (id)initWithCode:(unsigned int)arg1 properties:(id)arg2 data:(id)arg3;
- (unsigned int)codeInContext:(id)arg1;
- (id)description;

@end

@interface SBProxyByClass : SBProxy
{
    Class _classToCreate;
}

- (id)initWithClass:(Class)arg1 properties:(id)arg2 data:(id)arg3;
- (unsigned int)codeInContext:(id)arg1;
- (id)description;

@end

@interface SBProxy : NSProxy
{
    SBObject *_createdObject;
    NSDictionary *_properties;
    id _data;
}

- (void)dealloc;
- (unsigned int)codeInContext:(id)arg1;
- (void)addAtInsertionLocation:(const struct AEDesc *)arg1 inContext:(id)arg2;
- (void)addAtLocation:(id)arg1;
- (void)addAfterObjectsOfClass:(Class)arg1 inContainer:(id)arg2;
- (BOOL)respondsToSelector:(SEL)arg1;
- (void)forwardInvocation:(id)arg1;
- (id)methodSignatureForSelector:(SEL)arg1;
- (void)doesNotRecognizeSelector:(SEL)arg1;
- (BOOL)exists;
- (id)description;
- (id)debugDescription;

@end

@interface SBRelativePosition : SBObject
{
}

- (id)initWithParent:(id)arg1 position:(int)arg2;
- (id)get;

@end

@interface SBAppContext : NSObject
{
    SBApplication *_application;
    NSDictionary *_classNamesForCodes;
    NSDictionary *_codesForPropertyNames;
    NSDictionary *_codesForClassNames;
    NSDictionary *_propertyNamesForCodes;
    NSString *_name;
    id _delegate;
    SBAppLocator *_locator;
    int _sendMode;
    long long _timeout;
}

- (id)init;
- (id)initWithBundleIdentifier:(id)arg1;
- (id)initWithPID:(int)arg1;
- (id)initWithURL:(id)arg1;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;
- (id)classNamesForCodes;
- (id)codesForClassNames;
- (Class)classForCode:(unsigned int)arg1;
- (unsigned int)codeForClass:(Class)arg1;
- (id)codesForPropertyNames;
- (id)propertyNamesForCodes;
- (unsigned int)codeForPropertyName:(id)arg1;
- (id)propertyNameForCode:(unsigned int)arg1;
- (id)objectForDescriptor:(const struct AEDesc *)arg1 atIndex:(long long)arg2;
- (id)objectForDescriptor:(const struct AEDesc *)arg1;
- (id)descriptorForObject:(id)arg1;
- (id)descriptorForObject:(id)arg1 typeCode:(unsigned int)arg2;
- (short)createEmptyEvent:(struct AEDesc *)arg1 withClass:(unsigned int)arg2 id:(unsigned int)arg3;
- (id)processReply:(const struct AEDesc *)arg1 andError:(int)arg2 forEvent:(const struct AEDesc *)arg3;
- (id)sendEvent:(const struct AEDesc *)arg1;
- (void)setApplication:(id)arg1;
- (id)name;
- (id)path;
- (id)bundleIdentifier;
- (id)qualifiedSpecifier;
- (id)sdef;

@end

@interface SBRemoteURLAppLocator : SBAppLocator
{
    NSURL *_url;
}

- (id)initWithURL:(id)arg1;
- (id)path;
- (id)name;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)sdef;
- (id)description;

@end

@interface SBFilePathAppLocator : SBAppLocator
{
    NSString *_filePath;
}

- (id)initWithFilePath:(id)arg1;
- (void)dealloc;
- (const struct AEDesc *)launchWithFlags:(unsigned int)arg1;
- (const struct AEDesc *)addressWithoutLaunching;
- (id)path;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;

@end

@interface SBPIDAppLocator : SBAppLocator
{
    int _pid;
}

- (id)initWithPID:(int)arg1;
- (id)path;
- (id)bundleIdentifier;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;

@end

@interface SBIdentifiedAppLocator : SBAppLocator
{
    NSString *_bundleIdentifier;
}

- (id)initWithBundleIdentifier:(id)arg1;
- (void)dealloc;
- (const struct AEDesc *)launchWithFlags:(unsigned int)arg1;
- (const struct AEDesc *)addressWithoutLaunching;
- (id)path;
- (id)bundleIdentifier;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (id)description;

@end

@interface SBAppLocator : NSObject <NSCoding>
{
    struct AEDesc _address;
    unsigned int _launchFlags;
}

- (id)init;
- (void)finalize;
- (void)dealloc;
- (void)encodeWithCoder:(id)arg1;
- (id)initWithCoder:(id)arg1;
- (const struct AEDesc *)launchWithFlags:(unsigned int)arg1;
- (const struct AEDesc *)address;
- (const struct AEDesc *)addressWithoutLaunching;
- (void)resetAddress;
- (id)processInformation;
- (id)path;
- (id)name;
- (id)bundleIdentifier;
- (BOOL)isRunning;
- (id)sdef;
- (id)description;

@end

@interface NSDictionary (SBAppContextExtensions)
- (id)reverseDictionary;
@end

