#!/bin/sh

# Set up some git repo configuration

pushd ./`git rev-parse --show-cdup`/.git/hooks
ln -s ../../tools/pre-commit .
popd

pushd ./`git rev-parse --show-cdup`
mkdir wiki
git clone https://code.google.com/p/csshx.wiki/ wiki

# Note for Tagging:
#    git tag -a -m "Version 0.73" 0.73 HEAD
